POST http://localhost:9090/user/new
Content-Type: application/json

{ "email":"mdsd@mail.ru", "name":"Matvey", "city":"SPB" }

###
GET http://localhost:9090/user/2
Accept: application/json

###
POST http://localhost:9090/user/1/edit
Content-Type: application/json

{ "email":"a@mail.ru", "name":"Alex Matveev", "city":"Moscow City" }

###
GET http://localhost:9090/user/1
Accept: application/json

###